const data = [
  {
    id: 1,
    name: "Web & Mobile Design",
    desc: "We are providing best web and mobile design for you. We have a professional team to build an interactive and latest trend Design",
    level: "Standard",
    price: 100,
    img: "https://imgur.com/zcl4n49.png",
    item: [
      "Design Customization",
      "Content Upload",
      "Responsive Web Design",
      "Include Source Code",
      "3 - 5 Pages Design",
      "Using React",
      "Unlimited Revision",
      "Using Latest Technology",
    ],
  },
  {
    id: 2,
    name: "Graphic Design",
    desc: "Best Grapic Designers are waited for building latest trending designs for you. We provide designs in the cheapest price that you can use.",
    level: "Premium",
    price: 150,
    img: "https://imgur.com/JVqIaSO.png",
    item: [
      " 3 - 5 Design Samples",
      "Design Customization",
      "Content Upload",
      "Provind all format supported images",
      "Include Source Code",
      "Unlimited Revision",
      "Change content facilites",
    ],
  },
  {
    id: 3,
    name: "Web Development",
    desc: "Develop your web application, with our frontend and backend engineers. We willl provide best web application for you as soon as possible",
    level: "Premium",
    price: 200,
    img: "https://imgur.com/bdtcRiO.png",
    item: [
      "Design Customization",
      "Content Upload",
      "Responsive Web Design",
      "Include Source Code",
      "3 - 5 Pages Design",
      "MERN/MEAN Stack",
      "Unlimited Revision",
      "Using Latest Technology",
    ],
  },
];
