import Head from "next/head";
import Banner from "../components/Banner";
import PortfolioSection from "../components/PortfolioSection";
import ServiceSection from "../components/ServiceSection";
import Sponsor from "../components/Sponsor";
import FeedBack from "../components/FeedBack";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Creative Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Banner />
        <Sponsor />
        <ServiceSection />
        <PortfolioSection />
        <FeedBack />
      </main>
    </>
  );
}
